import "./styles/globals.scss";
import localFont from 'next/font/local'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Dirooz = localFont({ src: '../public/fonts/Dirooz.woff2' })

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={`bg-[#f3f3f3] ${Dirooz.className}`} >{children}</body>
    </html>
  );
}
